/**
 * Campaign Model
 *
 * COLUMNS
 * (pk) id        : int autoincrement (autogenerated)
 *      title      : string
 *      description: text
 *      createdAt : datetime          (autogenerated)
 *      modifiedAt : datetime          (autogenerated)
 * 
 */
const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const Campaign = sequelize.define(
    'Campaign',
    {
        titleFI: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        descriptionFI: {
            type: DataTypes.TEXT,
            allowNull: true,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
        titleSV: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        descriptionSV: {
            type: DataTypes.TEXT,
            allowNull: true,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
        titleEN: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        descriptionEN: {
            type: DataTypes.TEXT,
            allowNull: true,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
        categoryId: {
            type: DataTypes.SMALLINT,
            allowNull: true,
        },
        isPublic: {
            type: DataTypes.BOOLEAN,
            default: false,
        },
        visibleUntilDate: {
            type: DataTypes.DATE,
            allowNull: true,
        }
    },
    {
        timestamps: true,
    }
);
Campaign.associate = function(models) {
    // User that created the campaign
    Campaign.belongsTo(models.User, { foreignKey: 'userId' });
};

module.exports = Campaign;
