/**
 * Category Model
 *
 * COLUMNS
 * (pk) id        : int autoincrement (autogenerated)
 *      name      : string
 *      createdAt : datetime          (autogenerated)
 */
const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const Category = sequelize.define(
    'Category',
    {
        name: {
            type: DataTypes.STRING,
            allowNull: false,
        },
    },
    {
        timestamps: true,
        updatedAt: false, // we don't want updatedAt
    }
);

module.exports = Category;
