/**
 * Category Model
 *
 * COLUMNS
 * (pk) id        : int autoincrement (autogenerated)
 *      name      : string
 *      description: text
 *      createdAt : datetime          (autogenerated)
 * 
 */
const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const Category = sequelize.define(
    'Category',
    {
        nameFI: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        descriptionFI: {
            type: DataTypes.TEXT,
            allowNull: false,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
        nameSV: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        descriptionSV: {
            type: DataTypes.TEXT,
            allowNull: false,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
        nameEN: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        descriptionEN: {
            type: DataTypes.TEXT,
            allowNull: false,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
    },
    { indexes: [
            {unique:true, fields:['nameFI', 'nameSV','nameEN']}
        ]
    },
    {
        timestamps: true,
    }
);

Category.associate = function(models) {

    Category.hasMany(models.Memory, {
        foreignKey: 'categoryId'
    });

};

module.exports = Category;
