/**
 * Category Model
 *
 * COLUMNS
 * (pk) id        : int autoincrement (autogenerated)
 *      name      : string
 *      description: text
 *      createdAt : datetime          (autogenerated)
 * 
 */
const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const Category = sequelize.define(
    'Category',
    {
        name: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true,
        },
        description: {
            type: DataTypes.TEXT,
            allowNull: false,
            validate: {
                min: {
                    args: 10,
                    msg: 'Description has to be minimum 10 characters',
                },
            },
        },
    },
    {
        timestamps: true,
    }
);

module.exports = Category;
