/**
 * Category Memory
 *
 * COLUMNS
 * (pk) id          : int autoincrement (autogenerated)
 *      title       : string
 *      content     : text
 *      coordinates : geometry.point
 *      createdAt   : datetime          (autogenerated)
 *      iupdatedAt  : datetime          (autogenerated)
 *
 * ASSOCIATIONS
 * (fk) userID      : int               (autogenerated)
 * (fk) categoryID  : int               (autogenerated)
 */
const { DataTypes } = require('sequelize')
const sequelize = require('../config/db').sequelize

const Memory = sequelize.define(
  'Memory',
  {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        min: {
          args: 4,
          msg: 'Content has to be minimum 4 characters',
        },
        max: {
          args: 255,
          msg: 'Content has to be maximum 255 characters',
        },
      },
    },
    content: {
      type: DataTypes.TEXT,
      allowNull: false,
      validate: {
        min: {
          args: 10,
          msg: 'Content has to be minimum 10 characters',
        },
      },
    },
    coordinates: {
      type: DataTypes.GEOMETRY('POINT'),
      allowNull: false,
    },
  },
  {
    timestamps: true,
  },
)

Memory.associate = function(models) {
  //Memory posted by one user
  Memory.belongsTo(models.User)
  models.User.hasMany(Memory)

  //Memory have one category
  Memory.belongsTo(models.Category)
  models.Category.hasMany(Memory)
}

module.exports = Memory
