/**
 * Category Report
 *
 * COLUMNS
 * (pk) id          : int autoincrement (autogenerated)
 *      title       : string
 *      description : text
 *      createdAt   : datetime          (autogenerated)
 *      updatedAt   : datetime          (autogenerated)
 *      invalid     : boolean           (admin has marked the report as invalid)
 *      adminUserId : int               (admin user who select to invalidate the report)
 *
 * ASSOCIATIONS
 * (fk) userID      : int               (autogenerated)
 * (fk) memoryID    : int               (autogenerated)
 */
const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const Report = sequelize.define(
    'Report',
    {
        title: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        description: {
            type: DataTypes.TEXT,
            allowNull: false,
        },
        invalid: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            default: false
        },
        adminUserId: {
            type: DataTypes.STRING,
            allowNull: true,
        }
    },

    {
        timestamps: true,
    }
);
Report.associate = function(models) {
    //Memory reported
    Report.belongsTo(models.Memory, {
        foreignKey: 'memoryId',
    });

    //User that reported the memory
    Report.belongsTo(models.User, { foreignKey: 'userId' });
};

module.exports = Report;
