/**
 * Category Report
 *
 * COLUMNS
 * (pk) id          : int autoincrement (autogenerated)
 *      title       : string
 *      description : text
 *      createdAt   : datetime          (autogenerated)
 *
 * ASSOCIATIONS
 * (fk) userID      : int               (autogenerated)
 * (fk) memoryID    : int               (autogenerated)
 */
const { DataTypes } = require('sequelize')
const sequelize = require('../config/db').sequelize

const Report = sequelize.define(
  'Report',
  {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
  },

  {
    timestamps: true,
    updatedAt: false, // we don't want updatedAt
  },
)
Report.associate = function(models) {
  //Memory reported
  Report.belongsTo(models.Memory)
  models.Memory.hasMany(models.Report)

  //User that reported the memory
  Report.belongsTo(models.User)
  models.User.hasMany(Report)
}

module.exports = Report
