/**
 * Category User
 *
 * COLUMNS
 * (pk) id           : int autoincrement (autogenerated)
 *      username     : string
 *      email        : text
 *      passwordhash : char(60)
 *      googleID     : char(24) null
 *      facebookID   : bigint null
 *      createdAt    : datetime          (autogenerated)
 *      updatedAt    : datetime          (autogenerated)
 */

const { DataTypes } = require('sequelize');
const sequelize = require('../config/db').sequelize;

const User = sequelize.define(
    'User',
    {
        // Model attributes are defined here
        // No need to put id, it's automatic integer autoincrement
        // putting id here since we are using the ID we get from auth0. This ID can be used to identify users from each other
        displayName: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        id: {
            type: DataTypes.STRING,
            allowNull: false,
            primaryKey: true
        },
        username: {
            type: DataTypes.STRING,
            allowNull: true,
            unique: {
                args: true,
                msg: 'This username is taken',
            },
        },
        email: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: {
                isEmail: true,
            },
        },
        provider: {
            type: DataTypes.CHAR(24),
            allowNull: false
        },
        admin: {
            type: DataTypes.BOOLEAN,
            allowNull: false
        },
        yearOfBirth: {
            type: DataTypes.CHAR( 4),
            allowNull: true,
        },
    },
    
    {
        // Other model options go here
        timestamps: true, // automatically adds the fields createdAt and updatedAt to model
        // createdAt: false // if I don't want createdAt
        //updatedAt: 'updateTimestamp'// I want updatedAt to actually be called updateTimestamp
    }
);

module.exports = User;
